name: NPM Publish Libraries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: |
          echo Installing Dependencies
          sudo npm install -g npm-cli-login
          npm install
      - name: Run Pack
        run: |
          echo run lib:pack
          cd no-dissuasion-without-contact
          npm pack
          echo login to npm registry
          NPM_USER=michael-spengler NPM_PASS=${{ secrets.authToken }} NPM_EMAIL=michael@spengler.biz NPM_REGISTRY=https://npm.pkg.github.com NPM_SCOPE=@ams-pro npm-cli-login --verbose
          npm publish --verbose
